# Generated by Django 3.1.2 on 2023-05-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_productocarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carro',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductoCarro',
        ),
    ]
