# Generated by Django 3.1.2 on 2023-05-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20230518_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarroItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarro',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='itemcarro',
            name='producto',
        ),
        migrations.DeleteModel(
            name='CarroCompra',
        ),
        migrations.DeleteModel(
            name='ItemCarro',
        ),
        migrations.AddField(
            model_name='carrocompras',
            name='items',
            field=models.ManyToManyField(to='core.CarroItem'),
        ),
        migrations.AddField(
            model_name='carrocompras',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
