# Generated by Django 3.1.2 on 2023-05-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230520_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carroitem')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
            ],
        ),
    ]
