# Generated by Django 3.1.2 on 2023-05-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compraitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraitem',
            name='carro_item',
        ),
        migrations.AddField(
            model_name='compraitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
            preserve_default=False,
        ),
    ]
