# Generated by Django 3.1.2 on 2023-05-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230520_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraitem',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='compraitem',
            name='carro_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.carroitem'),
            preserve_default=False,
        ),
    ]
